### ISSUE TITLE
Condense the fallback case and regular case in `fallback`

### ISSUE THREAD

**Issue by JakeNavith** [JakeNavith/tailwindcss-theme-variants#1]
For example:

```js
{
  themes: {
    light: { mediaQuery: prefersLight },
    dark: { mediaQuery: prefersDark },
  },
  fallback: true
}
```

Generates this:
```css
bg-whatever {
  background-color: #whatever;
}

.light\:bg-whatever {
  background-color: #whatever;
}

/* This one isn't needed */
@media (prefers-color-scheme: light) {
  .light\:bg-whatever {
    background-color: #whatever;
  }
}

@media (prefers-color-scheme: dark) {
  .dark\:bg-whatever {
    background-color: #whatever;
  }
}
```

We can reclaim unnecessarily lost bytes by removing that unneeded case.
