### ISSUE TITLE
[JIT] group variants  like group-hover not working 

### ISSUE THREAD

**Issue by Kuirak** [JakeNavith/tailwindcss-theme-variants#14]
Hello, 

group variants like `group-hover` or `group-focus`  are generating wrong css with `tailwindcss-theme-variants` plugin. 
I don't know if it is a bug in this repo or  in tailwindcss JIT bug so I will cross post it

Here is a reproduction repo:
https://github.com/Kuirak/jit-tailwindcss-theme-variants/

Expected Output:
```css
:root.dark-theme .dark\:group:hover .dark\:group-hover\:bg-amber-300 {
	--tw-bg-opacity: 1;
	background-color: rgba(252, 211, 77, var(--tw-bg-opacity));
}
```

Output 
```css
:root.dark-theme .dark\:group:hover .group-hover\:bg-teal-300 {
	--tw-bg-opacity: 1;
	background-color: rgba(94, 234, 212, var(--tw-bg-opacity));
}

:root.dark-theme .dark\:group:hover .group-hover\:bg-amber-300 {
	--tw-bg-opacity: 1;
	background-color: rgba(252, 211, 77, var(--tw-bg-opacity));
}
```
