### ISSUE TITLE
Using both selectors and media-queries not working as expected.

### ISSUE THREAD

**Issue by mia-riezebos** [JakeNavith/tailwindcss-theme-variants#24]
In the docs on the website, there's a table specifying that if a selector matches, it takes precedence over any media query.

| match | neither | prefers-color-scheme: light | prefers-color-scheme: dark
| --- | --- | --- | --- |
| neither | none | cyan | navy |
| .cyan | cyan | cyan | cyan |
| .navy | navy | navy | navy |

> As previously noted, when a required selector is present, it takes precendence over the media queries. Stated another way, the media queries only matter when no selector matches.

The thing is, in my project, my themes are not behaving as described above.

My config is like such:
```js
// tailwind.config.cjs
// ...
	variants: {
		extend: {
			backgroundColor: ['schemes'],
			textColor: ['schemes'],
			fill: ['schemes'],
			stroke: ['schemes'],
			borderColor: ['schemes'],
			outlineColor: ['schemes'],
			ringColor: ['schemes'],
			ringOffsetColor: ['schemes'],
			boxShadow: ['schemes']
		}
	},
	plugins: [
		// ...
		// Color Schemes
		themeVariants({
			group: 'schemes',
			themes: {
				// Basic Dark / Light Themes
				dark: {
					mediaQuery: prefersDark,
					selector: "[data-theme='dark']",
				},

				light: {
					mediaQuery: prefersLight,
					selector: "[data-theme='light']",
				}

				// // Inverted Colors (make sure there's no compatibility issues with inverted colors)
				// 'colors-inverted': {
				// 	mediaQuery: colorsInverted
				// }
			},
			// baseSelector: 'html',
			// fallback: 'dark'
		}),
		// ...
	]
```

The generated CSS (for example on the light theme), looks like this:
```css
@media (prefers-color-scheme: light){
        :root[data-theme='light'] .light\:bg-other-green-300{
                --tw-bg-opacity: 1;
                background-color: rgb(134 239 172 / var(--tw-bg-opacity));
        }
}
```

and behaves as you would expect from the generated css; BOTH the media query AND the selector [data-theme='light'] have to match for the background to turn green.
